// Created by iWeb 2.0.4 local-build-20081021

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_1:new IWShadow({blurRadius:2,offset:new IWPoint(1.0000,0.0000),color:'#3a060f',opacity:1.000000}),shadow_0:new IWShadow({blurRadius:2,offset:new IWPoint(1.0000,-0.0000),color:'#3a060f',opacity:1.000000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,133),url:'Storia_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Storia_files/stroke_9.png'},{rect:new IWRect(1,-1,199,2),url:'Storia_files/stroke_10.png'},{rect:new IWRect(200,-1,2,2),url:'Storia_files/stroke_11.png'},{rect:new IWRect(200,1,2,133),url:'Storia_files/stroke_12.png'},{rect:new IWRect(200,134,2,2),url:'Storia_files/stroke_13.png'},{rect:new IWRect(1,134,199,2),url:'Storia_files/stroke_14.png'},{rect:new IWRect(-1,134,2,2),url:'Storia_files/stroke_15.png'}],new IWSize(201,135)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,0,4,225),url:'Storia_files/stroke.png'},{rect:new IWRect(-2,-2,4,2),url:'Storia_files/stroke_1.png'},{rect:new IWRect(2,-2,193,2),url:'Storia_files/stroke_2.png'},{rect:new IWRect(195,-2,4,2),url:'Storia_files/stroke_3.png'},{rect:new IWRect(195,0,5,225),url:'Storia_files/stroke_4.png'},{rect:new IWRect(195,225,5,3),url:'Storia_files/stroke_5.png'},{rect:new IWRect(2,225,193,3),url:'Storia_files/stroke_6.png'},{rect:new IWRect(-2,225,4,3),url:'Storia_files/stroke_7.png'}],new IWSize(197,226))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Storia_files/StoriaMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');fixAllIEPNGs('Media/transparent.gif');Widget.onload();applyEffects()}
function onPageUnload()
{Widget.onunload();}
